//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHU.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyRate
    {
        public int Id { get; set; }
        public int CurrencyId { get; set; }
        public double BuyRate { get; set; }
        public double SaleRate { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Currency Currency { get; set; }
    }
}
