//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHU.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.Prices = new HashSet<Prices>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public bool IsActive { get; set; }
        public bool IsInStock { get; set; }
        public int BrandId { get; set; }
        public string State { get; set; }
        public string Color { get; set; }
        public string TemperatureFrom { get; set; }
        public string TemperatureTo { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public string Usability { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prices> Prices { get; set; }
        public virtual Category Category { get; set; }
    }
}
